version: '3.8'

services:
  db:
    image: postgres:14  # Use the official PostgreSQL image
    container_name: NBA_MyGM_postgres_DB
    ports:
      - "5432:5432"  # Expose PostgreSQL port
    environment:
      POSTGRES_DB: ${POSTGRES_DB}  # Name of your database
      POSTGRES_USER: ${POSTGRES_USER}  # Username for PostgreSQL
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Strong password for PostgreSQL
      
    restart: always  # Restart container if it crashes
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist database data in a Docker volume

  web:
    build: .
    container_name: nba_django
    command: python manage.py runserver 0.0.0.0:8000  # Start Django server
    volumes:
      - .:/app  # Mount code into the container
    ports:
      - "8000:8000"  # Expose Django app
    depends_on:
      - db  # Ensure DB is started before Django app
    environment:
      DATABASE_HOST: db  # Point to the db container
      DATABASE_NAME: ${POSTGRES_DB}
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      

volumes:
  postgres_data:  # Named volume for PostgreSQL data persistence
