version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: NBA_MyGM_mssql
    ports:
      - "1433:1433"  # Expose MSSQL port
    environment:
      SA_PASSWORD: "CC42C1C66A34A90B8CA76AA56C16D712032FCD8926FABB5BB16E8309AA704245"  # Strong password for SA
      ACCEPT_EULA: "Y"  # Accept EULA for MSSQL Server
      MSSQL_PID: "Developer"  # Developer version
    restart: always  # Always restart MSSQL container
    volumes:
      - mssql_data:/var/opt/mssql  # Persist database data in a Docker volume

  web:
    build: .
    container_name: nba_django
    command: python manage.py runserver 0.0.0.0:8000  # Start Django server
    volumes:
      - .:/app  # Mount code into the container
    ports:
      - "8000:8000"  # Expose Django app
    depends_on:
      - db  # Ensure DB is started before Django app
    environment:
      DATABASE_HOST: db  # Point to the db container
      DATABASE_NAME: nba_database
      DATABASE_USER: sa
      DATABASE_PASSWORD: "CC42C1C66A34A90B8CA76AA56C16D712032FCD8926FABB5BB16E8309AA704245"

volumes:
  mssql_data:  # Named volume for MSSQL data persistence
